In [15]:
# The usual preamble
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt

# Make the graphs a bit prettier, and bigger
pd.set_option('display.mpl_style', 'default')

# This is necessary to show lots of columns in pandas 0.12. 
# Not necessary in pandas 0.13.
pd.set_option('display.width', 5000) 
pd.set_option('display.max_columns', 60)

plt.rcParams['figure.figsize'] = (15, 5)

In [16]:
python_input_file1="C:/Users/ciapponil/Desktop/input_jupyter/lpt.csv"
test_lpt=pd.read_csv(python_input_file1, sep=';', nrows=10)

In [18]:
test_lpt[:5]

                     ds_elite.log_pagetagging.rowkey ds_elite.log_pagetagging.abtesth ds_elite.log_pagetagging.action ds_elite.log_pagetagging.actioncontext ds_elite.log_pagetagging.cacheversion ds_elite.log_pagetagging.code10  ds_elite.log_pagetagging.code8 ds_elite.log_pagetagging.device ds_elite.log_pagetagging.deviceso ds_elite.log_pagetagging.dt_loglocal ds_elite.log_pagetagging.dt_utc            ds_elite.log_pagetagging.filename ds_elite.log_pagetagging.httpmethod ds_elite.log_pagetagging.ip ds_elite.log_pagetagging.landingpage ds_elite.log_pagetagging.latitude ds_elite.log_pagetagging.longitude ds_elite.log_pagetagging.nationurl ds_elite.log_pagetagging.originaldevice ds_elite.log_pagetagging.page ds_elite.log_pagetagging.querystring                   ds_elite.log_pagetagging.rawline                  ds_elite.log_pagetagging.referrer ds_elite.log_pagetagging.regionname ds_elite.log_pagetagging.sitecountry ds_elite.log_pagetagging.sitedivision ds_elite.log_pagetagging.store ds_elite.log_pagetagging.subpage  ds_elite.log_pagetagging.thankyouordernumber ds_elite.log_pagetagging.timestmp  ds_elite.log_pagetagging.tpvalue_referrer ds_elite.log_pagetagging.uriorigin       ds_elite.log_pagetagging.uristem                 ds_elite.log_pagetagging.useragent ds_elite.log_pagetagging.usercountry ds_elite.log_pagetagging.version ds_elite.log_pagetagging.virtualsession     ds_elite.log_pagetagging.yedgesession                      ds_elite.log_pagetagging.ytos
0  100:all:balenciaga:2015-09-22:14:55:08.000 -07...           AhIBPf973IgpRNJZAbmMyg                             NaN                                    NaN       f31-258-balenciaga-prevenv-prod                      44765728NX                        44765728                      smartphone                           Android        2015-09-22:14:55:08.000 -0700   2015-09-22:21:55:08.000 +0000  bal_318710.esw3cch_S.201509222300-2400-0.gz                                 GET                 172.56.7.72                                   no                        32.736.240                        -96.886.950                                 us                              smartphone                      ItemPage                                    -  2015-09-22\t21:55:08\t172.56.7.72\tGET\twww.ba...             http://www.balenciaga.com/us/men/shoes                               Texas                                   US                            BALENCIAGA                     balenciaga                         ItemPage                                           NaN                       1,44296E+12                                        NaN                 www.balenciaga.com  /us/arena-sneakers_cod44765728nx.html  Mozilla/5.0 (Linux; Android 5.0.2; LGMS345 Bui...                                   US          2015-09-21-6b481b03c7f4        75a00c951f3772ca56650f93b96c985f  2c1eced8903b000095cd0156b0110b00b80f0000  959c154c06f1419aaa6579d36a535366n5DftHCIBx6mH8...
1  100:all:balenciaga:2015-09-22:15:59:36.000 -07...           AhIBPf973IgpRNJZAbmMyg                             NaN                                    NaN       f31-258-balenciaga-prevenv-prod                             NaN                             NaN                      smartphone                             Apple        2015-09-22:15:59:36.000 -0700   2015-09-22:22:59:36.000 +0000  bal_318709.esw3cch_S.201509230000-0100-0.gz                                 GET                 45.25.37.72                                   no                        32.833.460                        -96.791.950                                 us                              smartphone                    SearchPage                                    -  2015-09-22\t22:59:36\t45.25.37.72\tGET\twww.ba...  http://www.balenciaga.com/us?tp=62532&targetid...                               Texas                                   US                            BALENCIAGA                     balenciaga                         handbags                                           NaN                       1,44296E+12                                      62532                 www.balenciaga.com                     /us/women/handbags  Mozilla/5.0 (iPhone; CPU iPhone OS 9_0 like Ma...                                   US          2015-09-21-6b481b03c7f4        72e6f44e42abd2f374810a8880af6758  270610609b01000048dd0156736d0b0038640100  b12ce7da4e744b5d8b124b10ac8f7de29gXfe5fhCtIf8m...
2  100:all:balenciaga:2015-09-22:16:45:02.000 -08...           AhIBPf973IgpRNJZAbmMyg                             NaN                                    NaN       f31-258-balenciaga-prevenv-prod                      44765622UD                        44765622                         desktop                           Windows        2015-09-22:16:45:02.000 -0800   2015-09-23:00:45:02.000 +0000  bal_318710.esw3cch_S.201509230100-0200-0.gz                                 GET              66.202.183.222                                   no                        33.919.180                       -118.416.470                                 ca                                 desktop                      ItemPage                                    -  2015-09-23\t00:45:02\t66.202.183.222\tGET\twww...             http://www.balenciaga.com/ca/men/shoes                          California                                   CA                            BALENCIAGA                     balenciaga                         ItemPage                                           NaN                       1,44297E+12                                        NaN                 www.balenciaga.com  /ca/arena-sneakers_cod44765622ud.html  Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) G...                                   US          2015-09-21-6b481b03c7f4        6bfb5b6e8b3d32440fefb057b7b99be3  913819b871030000dff50156618e040009160200  1008f1988aa340f6b8fcbdee92488f52NiRlfrRbMlQ17k...
3  100:all:balenciaga:2015-09-22:17:40:07.000 -05...           AhIBPf973IgpRNJZAbmMyg                             NaN                                    NaN       f31-258-balenciaga-prevenv-prod                      44807767SV                        44807767                      smartphone                             Apple        2015-09-22:17:40:07.000 -0500   2015-09-22:22:40:07.000 +0000  bal_318710.esw3cch_S.201509222300-2400-0.gz                                 GET              173.66.239.141                                   no                        38.980.670                        -76.936.920                                 us                              smartphone                      ItemPage                                    -  2015-09-22\t22:40:07\t173.66.239.141\tGET\twww...           http://www.balenciaga.com/us/women/shoes                            Maryland                                   US                            BALENCIAGA                     balenciaga                         ItemPage                                           NaN                       1,44296E+12                                        NaN                 www.balenciaga.com      /us/race-shoes_cod44807767sv.html  Mozilla/5.0 (iPhone; CPU iPhone OS 8_1 like Ma...                                   US          2015-09-21-6b481b03c7f4        2a30b359751c542c2230ded3c43f20c6  642c1ab80f72000081d8015664da050019e20300  07790aad6b37409db922168ebf07efd4WEtOaLHViUm54b...
4  100:all:balenciaga:2015-09-22:17:40:45.000 -05...           AhIBPf973IgpRNJZAbmMyg                             NaN                                    NaN       f31-258-balenciaga-prevenv-prod                      44895472SF                        44895472                             NaN                             Apple        2015-09-22:17:40:45.000 -0500   2015-09-22:22:40:45.000 +0000  bal_318710.esw3cch_S.201509222300-2400-0.gz                                 GET                172.72.203.1                                   no                        35.227.090                        -80.843.130                                 us                                     NaN                      ItemPage                                    -  2015-09-22\t22:40:45\t172.72.203.1\tGET\twww.b...             http://www.balenciaga.com/us/men/shoes                      North Carolina                                  NaN                                   NaN                     balenciaga                         ItemPage                                           NaN                       1,44296E+12                                        NaN                 www.balenciaga.com     /us/other-shoes_cod44895472sf.html  Mozilla/5.0 (iPhone; CPU iPhone OS 8_4_1 like ...                                   US          2015-09-21-6b481b03c7f4        56bc1dfed075da80f2567d11a16d1456                                       NaN  d517806cad4d49549f8c08bfe7bb3db1FwqZKXxKpOvnNR...

In [11]:
python_input_file2="C:/Users/ciapponil/Desktop/input_jupyter/LPT_TPvalue_REFERRER_query_result.csv"
LPT_TPvalue_REFERRER=pd.read_csv(python_input_file2, sep=',')

In [19]:
LPT_TPvalue_REFERRER

     ds_elite.a_lpt_tpvalue_referrer.sitedivision ds_elite.a_lpt_tpvalue_referrer.store ds_elite.a_lpt_tpvalue_referrer.tpvalue_referrer  ds_elite.a_lpt_tpvalue_referrer._c3
0                                             NaN                                   amq                                              NaN                               114588
1                                             NaN                                   amq                                           101592                                   14
2                                             NaN                                   amq                                           111279                                    1
3                                             NaN                                   amq                                           115423                                  146
4                                             NaN                                   amq                                           115537                                    5
5                                             NaN                                   amq                                           115984                                    5
6                                             NaN                                   amq                                           116205                                   56
7                                             NaN                                   amq                                           116206                                    3
8                                             NaN                                   amq                                           116561                                   37
9                                             NaN                                   amq                                           116562                                   10
10                                            NaN                                   amq                                           116577                                   18
11                                            NaN                                   amq                                           116578                                    3
12                                            NaN                                   amq                                           116939                                   18
13                                            NaN                                   amq                                           116940                                    1
14                                            NaN                                   amq                                           117027                                   46
15                                            NaN                                   amq                                           117029                                    1
16                                            NaN                                   amq                                            51969                                    2
17                                            NaN                                   amq                                            51970                                   25
18                                            NaN                                   amq                                            52066                                    1
19                                            NaN                                   amq                                            52067                                    2
20                                            NaN                                   amq                                            52068                                    6
21                                            NaN                                   amq                                            53592                                   55
22                                            NaN                                   amq                                            53593                                   39
23                                            NaN                                   amq                                            53594                                   34
24                                            NaN                                   amq                                            53595                                   92
25                                            NaN                                   amq                                            53596                                    3
26                                            NaN                                   amq                                            53597                                  311
27                                            NaN                                   amq                                            53598                                  494
28                                            NaN                                   amq                                            59529                                    1
29                                            NaN                                   amq                                            62564                                11105
...                                           ...                                   ...                                              ...                                  ...
1382                              STELLAMCCARTNEY                       stellamccartney                                            73186                                    4
1383                              STELLAMCCARTNEY                       stellamccartney                                            74139                                    1
1384                              STELLAMCCARTNEY                       stellamccartney                                            74284                                   42
1385                              STELLAMCCARTNEY                       stellamccartney                                            74606                                    1
1386                              STELLAMCCARTNEY                       stellamccartney                                            75589                                    3
1387                              STELLAMCCARTNEY                       stellamccartney                                            75789                                    1
1388                              STELLAMCCARTNEY                       stellamccartney                                            75922                                  494
1389                              STELLAMCCARTNEY                       stellamccartney                                            76580                                   12
1390                              STELLAMCCARTNEY                       stellamccartney                                            78582                                    1
1391                              STELLAMCCARTNEY                       stellamccartney                                            78733                                    1
1392                              STELLAMCCARTNEY                       stellamccartney                                            80497                                   59
1393                              STELLAMCCARTNEY                       stellamccartney                                   80497?tp=80497                                   12
1394                              STELLAMCCARTNEY                       stellamccartney                                            80702                                 9900
1395                              STELLAMCCARTNEY                       stellamccartney                                            80703                                 7999
1396                              STELLAMCCARTNEY                       stellamccartney                                            80704                                  165
1397                              STELLAMCCARTNEY                       stellamccartney                                            82973                                    2
1398                              STELLAMCCARTNEY                       stellamccartney                                            90710                                 1333
1399                              STELLAMCCARTNEY                       stellamccartney                                            96505                                   18
1400                              STELLAMCCARTNEY                       stellamccartney                                            96508                                  482
1401                              STELLAMCCARTNEY                       stellamccartney                                            96533                                 1607
1402                              STELLAMCCARTNEY                       stellamccartney                                            96659                                    5
1403                              STELLAMCCARTNEY                       stellamccartney                                            97544                                 1347
1404                              STELLAMCCARTNEY                       stellamccartney                                            97549                                    1
1405                              STELLAMCCARTNEY                       stellamccartney                                            97706                                  486
1406                              STELLAMCCARTNEY                       stellamccartney                                            97939                                    1
1407                              STELLAMCCARTNEY                       stellamccartney                                            99193                                    1
1408                             STELNGID=19&SITE                       stellamccartney                                              NaN                                    1
1409                              STELOAMCCARTNEV                       stellamccartney                                              NaN                                    1
1410                                bottegaveneta                         bottegaveneta                                              NaN                                    1
1411                                 saintlaurent                                   ysl                                              NaN                                   39

[1412 rows x 4 columns]